Repository testing-library/dom-testing-library, pull requests merged in 2020-05, with the labels that each got.

#550 fix: Exclude container in the list of queryable roles
  src/__tests__/role.js
  src/queries/role.js
Labels: bug

#540 feat(ByRole): Allow filter by selected state
  src/__tests__/ariaAttributes.js
  src/queries/role.js
  src/role-helpers.js
Labels: enhancement

#568 fix: Consider explicit role when pretty printing roles
  src/__tests__/role.js
  src/role-helpers.js
Labels: bug

#574 fix(types): add fourth param to build findAllBy and findBy queries
  types/__tests__/type-tests.ts
  types/query-helpers.d.ts
Labels: TypeScript, bug

#580 fix: Consider <caption> and <legend>
  package.json
Labels: bug

#586 feat: suggestions for which query to use
  src/__tests__/suggestions.js
  src/config.js
  src/index.js
  src/queries/alt-text.js
  src/queries/display-value.js
  src/queries/label-text.js
  src/queries/placeholder-text.js
  src/queries/role.js
  src/queries/test-id.js
  src/queries/text.js
  src/queries/title.js
  src/query-helpers.js
  src/suggestions.js
  src/wait-for.js
  types/index.d.ts
  types/matches.d.ts
  types/suggestions.d.ts
Labels: enhancement
