Repository testing-library/dom-testing-library, pull requests merged in 2020-03, with the labels that each got.

#408 feat(byRole): Add `name` filter
  package.json
  src/__tests__/__snapshots__/role-helpers.js.snap
  src/__tests__/role.js
  src/queries/role.js
  src/role-helpers.js
Labels: enhancement

#446 fix: Various implicit roles in ByRole
  package.json
  src/__tests__/__snapshots__/role-helpers.js.snap
  src/__tests__/element-queries.js
  src/__tests__/role-helpers.js
  src/__tests__/role.js
  src/role-helpers.js
Labels: bug

#373 Add more robust selector handling for getByLabelText
  src/__tests__/element-queries.js
  src/queries/label-text.js
Labels: BREAKING CHANGE

#415 feat(wait): wait will now also run your callback on DOM changes
  package.json
  src/__tests__/fake-timers.js
  src/__tests__/pretty-dom.js
  src/__tests__/role-helpers.js
  src/__tests__/screen.js
  src/__tests__/wait-for-dom-change.js
  src/__tests__/wait-for-element-to-be-removed.js
  src/__tests__/wait-for-element.js
  src/__tests__/wait.js
  src/config.js
  src/pretty-dom.js
  src/role-helpers.js
  src/wait-for-dom-change.js
  src/wait-for-element-to-be-removed.js
  src/wait-for-element.js
  src/wait.js
  tests/setup-env.js
Labels: BREAKING CHANGE

#463 fix(allByLabelText): forEach on NodeList is not supported in edge
  src/queries/label-text.js
Labels: bug

#464 fix(prettyRoles): crash in older browsers
  src/role-helpers.js
Labels: bug

#487 fix(allByLabelText): forEach on NodeList is not supported in edge
  src/queries/label-text.js
Labels: bug

#496 fix(fireEvent): Set composed property on relevant synthetic events
  src/__tests__/events.js
  src/event-map.js
  src/events.js
Labels: bug
